version: "3"
services:
    postgres:
        image: postgres
        container_name: postgres
        restart: always
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment: 
            - POSTGRES_DB=onlinejudge
            - POSTGRES_PASSWORD=password
    
    backend:
        build: ./MainServer
        container_name: onlinejudge
        restart: always
        volumes:
            - ./data/testcases:/testcases
        depends_on: 
            - postgres
        environment: 
            - DATABASE_URL=postgresql://postgres:password@postgres/postgres
            - REDIS_URL=redis://redis:6379
        ports:
            - 5000:5000
    
    # Only use in production, comment out in development
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        volumes:
            - ./deployment/nginx.conf:/etc/nginx/conf.d/default.conf
            - /etc/letsencrypt/live/staoj.com/fullchain.pem:/etc/letsencrypt/live/staoj.com/fullchain.pem
            - /etc/letsencrypt/live/staoj.com/privkey.pem:/etc/letsencrypt/live/staoj.com/privkey.pem
            - ./MainServer/app/static:/static
        ports:
            - 80:80
            - 443:443
        links:
            - backend

    redis:
        image: redis
        container_name: redis
        restart: always
        volumes: 
            - ./data/redis:/data
        ports:
            - 6379:6379

    autograder:
        build: ./JudgeServer
        container_name: autograder
        restart: always
        read_only: true
        tmpfs:
            - /tmp
        volumes:
            - ./data/testcases:/testcases
            - ./data/autograder/run:/judger
            - ./data/autograder/log:/log
        cap_drop:
            - SETPCAP
            - MKNOD
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
            - FSETID
        depends_on: 
            - redis
            - postgres
        environment:
            - LC_ALL=C.UTF-8
            - LANG=C.UTF-8
            - DATABASE_URL=postgresql://postgres:password@postgres/postgres